"""Pydantic schemas."""
from app.schemas.schemas import (
    # Enums
    WorkOrderStatus,
    StepStatus,
    DeviceStatus,
    BOMStatus,
    # Supplier
    SupplierBase,
    SupplierCreate,
    SupplierUpdate,
    SupplierResponse,
    # Component
    ComponentBase,
    ComponentCreate,
    ComponentUpdate,
    ComponentResponse,
    StockAdjustment,
    # BOM
    BOMItemBase,
    BOMItemCreate,
    BOMItemResponse,
    BOMBase,
    BOMCreate,
    BOMUpdate,
    BOMResponse,
    # Work Order Step
    WorkOrderStepBase,
    WorkOrderStepCreate,
    WorkOrderStepResponse,
    # Work Order
    WorkOrderBase,
    WorkOrderCreate,
    WorkOrderUpdate,
    WorkOrderResponse,
    # Device
    PLCharacteristics,
    QCMeasurement,
    QCRecord,
    BuildHistoryItem,
    CustomerInfo,
    DeviceBase,
    DeviceCreate,
    DeviceUpdate,
    DeviceResponse,
    SaleData,
    ShipData,
    PaymentData,
    # Quality Check
    QualityCheckCreate,
    QualityCheckResponse,
    # Component Usage
    ComponentUsageCreate,
    ComponentUsageResponse,
    # History
    DeviceHistory,
)

__all__ = [
    "WorkOrderStatus",
    "StepStatus",
    "DeviceStatus",
    "BOMStatus",
    "SupplierBase",
    "SupplierCreate",
    "SupplierUpdate",
    "SupplierResponse",
    "ComponentBase",
    "ComponentCreate",
    "ComponentUpdate",
    "ComponentResponse",
    "StockAdjustment",
    "BOMItemBase",
    "BOMItemCreate",
    "BOMItemResponse",
    "BOMBase",
    "BOMCreate",
    "BOMUpdate",
    "BOMResponse",
    "WorkOrderStepBase",
    "WorkOrderStepCreate",
    "WorkOrderStepResponse",
    "WorkOrderBase",
    "WorkOrderCreate",
    "WorkOrderUpdate",
    "WorkOrderResponse",
    "PLCharacteristics",
    "QCMeasurement",
    "QCRecord",
    "BuildHistoryItem",
    "CustomerInfo",
    "DeviceBase",
    "DeviceCreate",
    "DeviceUpdate",
    "DeviceResponse",
    "SaleData",
    "ShipData",
    "PaymentData",
    "QualityCheckCreate",
    "QualityCheckResponse",
    "ComponentUsageCreate",
    "ComponentUsageResponse",
    "DeviceHistory",
]
